---
name: Build and Push to ECR

'on':
  push:
    branches: [stacklok-main]
    paths:
      - 'Dockerfile'
      - 'helm/librechat/values.yaml'
      - 'helm/librechat/**'
      - 'helm/librechat-rag-api/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 781189302813.dkr.ecr.us-east-1.amazonaws.com

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::781189302813:role/github-actions-research
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata for images
        id: meta
        run: |
          VERSION=$(grep 'tag:' helm/librechat/values.yaml | \
            awk -F'"' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push LibreChat image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: >-
            ${{ env.ECR_REGISTRY }}/librechat:${{ steps.meta.outputs.version }}

      - name: Build and push MongoDB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/mongodb/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/mongodb:8.0.3

      - name: Build and push Meilisearch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/meilisearch/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/meilisearch:v1.7.3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'

      - name: Package Helm Charts
        run: |
          # Package LibreChat chart
          helm dependency update helm/librechat
          helm package helm/librechat

          # Package LibreChat RAG API chart
          helm dependency update helm/librechat-rag-api
          helm package helm/librechat-rag-api

      - name: Push Helm Charts to ECR
        run: |
          # Create ECR repository for Helm if it doesn't exist
          aws ecr describe-repositories --repository-names helm-charts || \
            aws ecr create-repository --repository-name helm-charts

          # Push LibreChat chart
          LIBRECHAT_CHART=$(ls librechat-*.tgz)
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
            helm registry login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
          helm push $LIBRECHAT_CHART oci://${{ env.ECR_REGISTRY }}/helm-charts/

          # Push LibreChat RAG API chart
          RAG_CHART=$(ls librechat-rag-api-*.tgz)
          helm push $RAG_CHART oci://${{ env.ECR_REGISTRY }}/helm-charts/
