name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'helm/librechat/values.yaml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 781189302813.dkr.ecr.us-east-1.amazonaws.com

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata for images
        id: meta
        run: |
          VERSION=$(grep 'tag:' helm/librechat/values.yaml | awk -F'"' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push LibreChat image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/librechat:${{ steps.meta.outputs.version }}

      - name: Build and push MongoDB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/mongodb/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/mongodb:8.0.3

      - name: Build and push Meilisearch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/meilisearch/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/meilisearch:v1.7.3

      - name: Update Helm values with new image tags
        run: |
          VERSION=${{ steps.meta.outputs.version }}
          sed -i "s|tag: .*|tag: \"${VERSION}\"|" helm/librechat/values.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add helm/librechat/values.yaml
          git commit -m "Update image tags to ${VERSION}"
          git push
